### PR TITLE
Adding sits to kubecf test suite

### PR DESCRIPTION
**Pull request by bikramnehra**

### CODE REVIEW

**Comment by viccuad** [comment]
many thanks! this is awesome. Rebased on top of mix fix in master for my silly quoting mistake.

**Comment by mudler** [comment]
With the changes on top, I'm able to trigger it correctly (but they are failing, but I guess it's another story)

```❯ kubectl get qjobs -n scf                                                                                                                                                                    
NAME                                AGE                                                                                                                                                       
dm-susecf-scf                       55m                                                                                                                                                       
ig-susecf-scf                       55m                                                                                                                                                       
susecf-scf-acceptance-tests         32m
susecf-scf-brain-tests              32m
susecf-scf-configure-eirini         33m
susecf-scf-rotate-cc-database-key   33m
susecf-scf-smoke-tests              33m
susecf-scf-sync-integration-tests   32m
```
and:

```make -s -C modules/tests kubecf
~/_git/catapult/buildactivepassive ~/_git/catapult/modules/tests
[1;34mℹ  [1;37m🚀  [40mkind [1;35m☸ activepassive [0;94m 🎂  ./kubecf-test.sh[1;34m ➤  [1;37m[40mLoading[0m
No resources found
~/_git/kubecf ~/_git/catapult/buildactivepassive ~/_git/catapult/modules/tests
quarksjob.quarks.cloudfoundry.org/susecf-scf-sync-integration-tests patched (no change)
[1;34mℹ  [1;37m🚀  [40mkind [1;35m☸ activepassive [0;94m 🎂  ./kubecf-test.sh[1;34m ➤  [1;37m[40mWaiting for the sync-integration-tests pod to start...[0m
pod/susecf-scf-sync-integration-tests-31a11969290bd92d-kdqt2
~/_git/catapult/buildactivepassive ~/_git/catapult/modules/tests
[1;34mℹ  [1;37m🚀  [40mkind [1;35m☸ activepassive [0;94m 🎂  ./kubecf-test.sh[1;34m ➤  [1;37m[40mWaiting for container sync-integration-tests-sync-integration-tests in pod/susecf-scf-sync-integration-tests-31a11969290bd92d-kdqt2[0m
################################################################################################################
go version go1.13.7 linux/amd64
[..]
################################################################################################################
Running sync integration tests...
Running Suite: SITS Suite
=========================
Random Seed: [1m1583316324[0m - Will randomize all specs
Will run [1m11[0m specs

Running in parallel across [1m4[0m nodes

{"timestamp":"1583316332.328673601","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":1,"session":"1"}}
{"timestamp":"1583316332.328731298","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":1,"session":"1"}}
{"timestamp":"1583316332.328897715","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316332.328897715","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
Error from server (NotFound): services "scf-diego-api" not found
{"timestamp":"1583316332.829025745","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":2,"session":"1"}}
{"timestamp":"1583316332.829102993","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":2,"session":"1"}}
{"timestamp":"1583316332.829302311","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316332.829302311","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316333.329427004","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":3,"session":"1"}}
{"timestamp":"1583316333.329499483","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":3,"session":"1"}}
{"timestamp":"1583316333.329726934","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316333.329726934","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316338.832298517","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":1,"session":"2"}}
{"timestamp":"1583316338.832509995","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":1,"session":"2"}}
{"timestamp":"1583316338.832948446","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316338.832948446","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316339.333127737","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":2,"session":"2"}}
{"timestamp":"1583316339.333208084","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":2,"session":"2"}}
{"timestamp":"1583316339.333507299","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316339.333507299","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316339.833683968","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":3,"session":"2"}}
{"timestamp":"1583316339.833781242","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":3,"session":"2"}}
{"timestamp":"1583316339.834200621","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316339.834200621","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}


[91m[1mFailure [10.008 seconds][0m
[91m[1m[BeforeSuite] BeforeSuite [0m
[37m/var/vcap/packages/sync-integration-tests/src/code.cloudfoundry.org/sync-integration-tests/sync_integration_suite_test.go:100[0m

  [91mTimed out after 10.000s.
  Unable to reach BBS at https://127.0.0.1:8889
  Expected
      <bool>: false
  to be true[0m

  /var/vcap/packages/sync-integration-tests/src/code.cloudfoundry.org/sync-integration-tests/sync_integration_suite_test.go:134
[90m------------------------------[0m
{"timestamp":"1583316332.367829800","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":1,"session":"1"}}
{"timestamp":"1583316332.367887497","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":1,"session":"1"}}
{"timestamp":"1583316332.368062019","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316332.368062019","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316332.868201733","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":2,"session":"1"}}
{"timestamp":"1583316332.868335724","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":2,"session":"1"}}
{"timestamp":"1583316332.869112730","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316332.869112730","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316333.369270563","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":3,"session":"1"}}
{"timestamp":"1583316333.369364977","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":3,"session":"1"}}
{"timestamp":"1583316333.369849920","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316333.369849920","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316338.870182991","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":1,"session":"2"}}
{"timestamp":"1583316338.870292187","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":1,"session":"2"}}
{"timestamp":"1583316338.870714426","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316338.870714426","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316339.370915890","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":2,"session":"2"}}
{"timestamp":"1583316339.371014118","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":2,"session":"2"}}
{"timestamp":"1583316339.371303797","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316339.371303797","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316339.871434212","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":3,"session":"2"}}
{"timestamp":"1583316339.871491909","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":3,"session":"2"}}
{"timestamp":"1583316339.871714354","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316339.871714354","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}


[91m[1mFailure [10.052 seconds][0m
[91m[1m[BeforeSuite] BeforeSuite [0m
[37m/var/vcap/packages/sync-integration-tests/src/code.cloudfoundry.org/sync-integration-tests/sync_integration_suite_test.go:100[0m

  [91mTimed out after 10.000s.
  Unable to reach BBS at https://127.0.0.1:8889
  Expected
      <bool>: false
  to be true[0m

  /var/vcap/packages/sync-integration-tests/src/code.cloudfoundry.org/sync-integration-tests/sync_integration_suite_test.go:134
[90m------------------------------[0m
{"timestamp":"1583316332.367462635","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":1,"session":"1"}}
{"timestamp":"1583316332.367521286","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":1,"session":"1"}}
{"timestamp":"1583316332.367698193","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316332.367698193","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316332.869080305","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":2,"session":"1"}}
{"timestamp":"1583316332.869219065","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":2,"session":"1"}}
{"timestamp":"1583316332.870558977","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316332.870558977","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316333.370723009","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":3,"session":"1"}}
{"timestamp":"1583316333.370819330","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":3,"session":"1"}}
{"timestamp":"1583316333.371364594","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316333.371364594","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316338.871611595","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":1,"session":"2"}}
{"timestamp":"1583316338.871702671","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":1,"session":"2"}}
{"timestamp":"1583316338.872099876","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316338.872099876","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316339.372215986","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":2,"session":"2"}}
{"timestamp":"1583316339.372252941","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":2,"session":"2"}}
{"timestamp":"1583316339.372532129","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316339.372532129","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316339.872672319","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":3,"session":"2"}}
{"timestamp":"1583316339.872756958","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":3,"session":"2"}}
{"timestamp":"1583316339.872935772","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316339.872935772","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}


[91m[1mFailure [10.053 seconds][0m
[91m[1m[BeforeSuite] BeforeSuite [0m
[37m/var/vcap/packages/sync-integration-tests/src/code.cloudfoundry.org/sync-integration-tests/sync_integration_suite_test.go:100[0m

  [91mTimed out after 10.000s.
  Unable to reach BBS at https://127.0.0.1:8889
  Expected
      <bool>: false
  to be true[0m

  /var/vcap/packages/sync-integration-tests/src/code.cloudfoundry.org/sync-integration-tests/sync_integration_suite_test.go:134
[90m------------------------------[0m
{"timestamp":"1583316332.370485544","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":1,"session":"1"}}
{"timestamp":"1583316332.370573997","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":1,"session":"1"}}
{"timestamp":"1583316332.370832920","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316332.370832920","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316332.870959759","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":2,"session":"1"}}
{"timestamp":"1583316332.871025085","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":2,"session":"1"}}
{"timestamp":"1583316332.871295691","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316332.871295691","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316333.371437311","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":3,"session":"1"}}
{"timestamp":"1583316333.371519566","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":3,"session":"1"}}
{"timestamp":"1583316333.371913910","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316333.371913910","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"1"}}
{"timestamp":"1583316338.872198582","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":1,"session":"2"}}
{"timestamp":"1583316338.872272491","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":1,"session":"2"}}
{"timestamp":"1583316338.872758389","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316338.872758389","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316339.372903109","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":2,"session":"2"}}
{"timestamp":"1583316339.372933149","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":2,"session":"2"}}
{"timestamp":"1583316339.373113632","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316339.373113632","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316339.873220682","source":"sits","message":"sits.do-request.creating-request","log_level":0,"data":{"attempt":3,"session":"2"}}
{"timestamp":"1583316339.873257399","source":"sits","message":"sits.do-request.doing-request","log_level":0,"data":{"attempt":3,"session":"2"}}
{"timestamp":"1583316339.873388767","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}
{"timestamp":"1583316339.873388767","source":"sits","message":"sits.do-request.failed-doing-request","log_level":2,"data":{"error":"Post https://127.0.0.1:8889/v1/ping: dial tcp 127.0.0.1:8889: connect: connection refused","session":"2"}}


[91m[1mFailure [10.052 seconds][0m
[91m[1m[BeforeSuite] BeforeSuite [0m
[37m/var/vcap/packages/sync-integration-tests/src/code.cloudfoundry.org/sync-integration-tests/sync_integration_suite_test.go:100[0m

  [91mTimed out after 10.000s.
  Unable to reach BBS at https://127.0.0.1:8889
  Expected
      <bool>: false
  to be true[0m

  /var/vcap/packages/sync-integration-tests/src/code.cloudfoundry.org/sync-integration-tests/sync_integration_suite_test.go:134
[90m------------------------------[0m

[1m[91mRan 44 of 0 Specs in 10.066 seconds[0m
[1m[91mFAIL![0m -- [32m[1m0 Passed[0m | [91m[1m44 Failed[0m | [33m[1m0 Flaked[0m | [33m[1m0 Pending[0m | [36m[1m0 Skipped[0m


There were failures detected in the following suites:
	[91msync-integration-tests[0m [37m.[0m

Ginkgo ran 1 suite in 17.873139294s
Test Suite Failed
```

**Comment by mudler** [comment]
For reference: I've deployed kubecf with https://github.com/cloudfoundry-incubator/kubecf/pull/436/commits/6178ade29b526101e14880ce7920bb4f2836f157 in

**Comment by mudler** [comment]
I think its fine to merge as-is, we can polish in other steps and move the qjob triggering to just call kubectl for the other test targets

**Pull request merged**
